site_name: 'autolog'
site_description: 'Main documentation for autolog'
repo_url: https://github.com/jaysuzi5/autolog
edit_uri: edit/main/docs

plugins:
  - techdocs-core

nav:
  - Overview:
      - Getting started: 'docs/index.md'